name: brew pr-pull

on:
  pull_request_target:
    types:
      - labeled

env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.OSX_CROSS_TESTS_HOMEBREW_GITHUB_API_TOKEN }}
  PULL_REQUEST: ${{ github.event.pull_request.number }}
  BRANCH: ${{ github.event.pull_request.head.ref }}

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        # uses: Homebrew/actions/git-user-config@master
        # with:
        #   username: osxCrossTestBot
        #   token: ${{ secrets.OSX_CROSS_TESTS_HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          brew install hub
          git config --global user.name "osxCrossTestBot"
          git config --global user.email "osxCrossTestBot@leka.io"
          git config --global hub.protocol https
          git config credential.helper '!f() { sleep 1; echo "username=osxCrossTestBot"; echo "password=${{ secrets.OSX_CROSS_TESTS_HOMEBREW_GITHUB_API_TOKEN }}"; }; f'
          hub fetch origin
          hub checkout master
          git reset --hard origin/master

      - name: Pull bottles
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: $${{ secrets.OSX_CROSS_TESTS_HOMEBREW_GITHUB_API_TOKEN }}
          branch: main

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        run: git push --delete origin $BRANCH
